site_name: My Docs

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: 
    - Overview: info.md
    - Key Concepts: concepts.md
    - Reference: api.md
    - Swagger UI: swagger/index.html

plugins:
  - search