site_name: My Docs

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
      - Overview: info.md
      - Key Concepts: concepts.md
      - Swagger UI: swagger

plugins:
  - search
  - swagger-ui-tag:
     background: White
